server:
  port: 10002
eureka:
  client:
    serviceUrl:
      defaultZone: http://rpm-elb-996808586.us-east-1.elb.amazonaws.com/rpm-eureka/eureka
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: '*'